services:
  - type: web
    name: labs-teleports-cloud
    runtime: python
    plan: free
    region: oregon
    branch: main
    rootDir: apps/python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python web_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
